### ISSUE TITLE
[Totally War II] Fix regions in spawn

### ISSUE THREAD

**Issue by fixitqixit** [OvercastCommunity/Issues#14]
# Map name
Totally War II

## Describe the bug
Based on player feedback, it appears that players can place blocks in team spawns. However these blocks can not be broken by newly spawned players.
### Additional context
This issue relates to a previous bug I attempted to fix with this map. Players were able to craft and place chests, however chests have a filter map-wide that denies their breakage. I implemented a minor fix through the crafting module. However this could be removed and fixed in a more orthodox way - along with the other issue specified in this post.

**Comment by CrazyisCreeps** [comment]
Issue is fixed in https://github.com/OvercastCommunity/PrivateMaps/commit/25c8ba82b377cd18b113c73f414170abb6054df7, had to do with an anti TNT filter that was applied to the spawn + nearby areas.
