### ISSUE TITLE
[Fox Strife] players can block wool monument

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastCommunity/Issues#16]
# Map name
Fox Strife

## Describe the bug
Players can block someone else from placing the wool on monument

## Expected behavior
to place block

**Comment by CrazyisCreeps** [comment]
How can players block the wool monuments?

**Comment by CoWinkKeyDinkInc** [comment]
If they stand near the monument in a certain way, it can block someone from placing a wool. This could be an issue with later versions of Minecraft

**Comment by CrazyisCreeps** [comment]
Honestly I wonder if this is something that can be fixed with the plugin rather than with maps. Editing every ctw xml in order to fix this would be a pain
