### ISSUE TITLE
[Red Agony] spawn issue

### ISSUE THREAD

**Issue by Diamyx** [OvercastCommunity/Issues#19]
# Map name
Red Agony

## Describe the bug
players sometimes get stuck in the ground when they spawn

## Screenshots
trust me

**Comment by CrazyisCreeps** [comment]
I raised the spawn up 0.5 of a block last night, has this behaviour happened since then?

**Comment by Diamyx** [comment]
yes @CrazyisCreeps

**Comment by CrazyisCreeps** [comment]
How do players manage to get stuck in the floor when they spawn above the floor now though? @Diamyx I'm having trouble recreating it
