### ISSUE TITLE
Implement spawn kits on TNT maps

### ISSUE THREAD

**Issue by fixitqixit** [OvercastCommunity/Issues#33]
## Maps that lack XML-given spawn kits
_Nostalgia maps_
- Airship Battle
- Airship Aces
- Fortress Battles
- Spaceship Battles
- Fort Wars
- Medieval Warfare
- Sky Traffic
- Sky Traffic 2
- Avalanche (may only need a small update)

_Newer maps_
- Donut Wars
- Hyperspace
- Airship Ascendence
- Medieval Warfare DTE (needs minor adjustments)

_Non-TNT maps that could need updates to base kits (if even present)_
- Cake Wars

_Apologies if I have missed any maps or I have mentioned any maps that don't need fixing. This is a very rough overview and I have not individually checked each of these maps for this exact issue._

## Is your feature request related to a problem?
Yes. Often these maps become a battle to destroy the other teams chests first, which isn't the objective of the map - the _objective_ (core, monument) is the objective of the map. To quote Strangey as well from the OCC discord (in #maps): 'resource wars should not happen on public matches... it turns into a one-sided game as one team is essentially an OP faction killing fresh people leaving their protected spawn with nothing' and 'some people enjoy scavenging to get stuff to do something but im sure a majority dont like that especially when some people will go out of their way to spawn kill instead of finishing the game'. 

## Describe the solution you'd like
I think there should also be enough resources to make a baseline defence. Too often these resources aren't available and its often hit or miss if someone on your team will go out of their way to build any form of defence. Some other suggestions are listed below:

## Describe alternatives you've considered
- food in the kits needs to match the original food source on the map (which a lot of the kits that haven’t recently been added don’t do)
- each kit should be similar to maps like Boombox or cos/other maps like that
- Certain maps which have specific and intentional tnt supply chests need to be factored into the decision about how much tnt is going to be in the kit, or if there is going to be any tnt in the kit at all
- this one is more experimental; make it so regular chests can not be destroyed or placed by any players on the map. If players want to use a form of storage they can be given trapped chests, which will be placeable and breakable. By using the <crafting> module the traditional crafting recipe for regular chests can instead give players trapped chests.
- I personally think the following things are a must* for kits: a water bucket, some tnt, 64 logs/4 stacks of blocks, cannoning items, a significant amount of food, and spawn protection (a definite must for preventing carpet bombers)
- This one is from Pablo: 'make a hidden non-required destroyable from the chests, that completes at 50%, and a spawn kit filtered on that objective, when the enemy team breaks half your supplies you start getting a kit with some extra things'

### Additional context
We need to create a welcoming space for new players if this server is to be sustainable. While these maps give off a nostalgic feeling and are often quite fun, the chaos and disorderly nature could be quite confusing and boring for new players (and not to mention many old players who are tired of these maps and their disorder).

**Comment by Brottweiler** [comment]
List of maps I have fixed spawnkit of

## TNT Maps
- [X] Airship Battle
- [X] Airship Aces
- [X] Fortress Battles
- [X] Spaceship Battles
- [ ] Spaceship Battles II
- [X] Fort Wars
- [X] Medieval Warfare
- [X] Sky Traffic
- [X] Sky Traffic 2
- [X] Avalanche
- [X] Donut Wars
- [X] Hyperspace
- [ ] Airship Ascendence
- [ ] Medieval Warfare DTE (needs minor adjustments)
- [X] Shroom Trip
- [X] Avalon Funland
- [X] D-Day
- [X] Iris DTC
- [X] Aerobellum
- [X] Battleship Halberd
- [X] Bridge Over Troubled Water
- [X] Runes of Ruin
- [X] Scribble Isle
- [X] Interitus

## Non-TNT maps
- [X] Cake Wars
- [X] A Watery Grave
- [X] Race For Victory

>This one is from Pablo: 'make a hidden non-required destroyable from the chests, that completes at 50%, and a spawn kit filtered on that objective, when the enemy team breaks half your supplies you start getting a kit with some extra things'

I think this is too confusing for players and kind of changes the map objective too much.
