### ISSUE TITLE
[Blocks: Destroy the Dynamite] You can damage your own team's monuments

### ISSUE THREAD

**Issue by RedstoneIsGreat** [OvercastCommunity/Issues#45]
# Map name
What map is affected by the bug?

**Blocks: Destroy the Dynamite**

## Describe the bug

**At least as of around a week ago or so, I discovered you could mine your own team's monument with a pickaxe. No "you may not damage your own objective" or similar message appears either. I am unsure if you can also damage your own team's monument with TNT or not.**

## Expected behavior

**It is expected that when you try to mine your own monument, a "you may not damage your own objective" or similar message appears, and if you still mine the block it reappears.**

**Comment by drmzio** [comment]
To confirm, you cannot damage your own monument with TNT. Just tried this and only blew up the outer layer.

**Comment by Pugzy** [comment]
All of the tops and one of the bottoms of the monuments (the endstone bits) were breakable.
This has now been fixed, you should be able to break the stained clay part of the TNT as the monument is made of endstone only.
