### ISSUE TITLE
[Ski Trip to Blizzardtown] Doors do not have disable use filter

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastCommunity/Issues#48]
# Map name
Ski Trip to Blizzardtown

## Describe the bug
Doors at spawn do not have a disable use filter on them to prevent team griefing.

## Expected behavior
Doors should have a filter added that prevents them being used, something like this I have in Miner Sixty Niner would work. https://github.com/OvercastCommunity/CommunityMaps/blob/master/Miner%20Sixty%20Niner/map.xml

```xml
 <union id="disable-fence">
        <cuboid min="-124,56,-57" max="-125,57,-54"/>
        <cuboid min="-125,56,36" max="-124,57,33"/>
        <cuboid min="-157,69,-6" max="-158,67,-15"/>
    </union>
    <apply use="never" region="disable-fence"/>
```

**Comment by CrazyisCreeps** [comment]
I'm pretty sure the doors are closed by default, meaning they'd have to be opened up if this filter would be used. Maybe @master00ofdsiware wants to do this?

**Comment by master00ofdsiware** [comment]
This should be fixed now, I'll keep an eye on it to make sure my fix worked.
