### ISSUE TITLE
[Kryta] The Nether Portal teleports you to the void

### ISSUE THREAD

**Issue by Jeeeezus** [OvercastCommunity/Issues#59]
Guessing this isn't intended

Before v
![2021-01-10_21 23 34](https://user-images.githubusercontent.com/76866752/104149567-7f864e80-538b-11eb-846a-f25c2e8c2244.png)

After v
![2021-01-10_21 23 40](https://user-images.githubusercontent.com/76866752/104149570-81e8a880-538b-11eb-874f-b95d9f2f9636.png)

**Comment by Jeeeezus** [comment]
also applies to one shot version pretty sure

**Comment by calcastor** [comment]
Here's a video showing the issue occur on Kryta: One Shot:

https://www.youtube.com/watch?v=VhEtDSg2FQw

**Comment by technodono** [comment]
can confirm that one shot kyrata also broken... these portals under spawn tp you off the map in the void
![image](https://user-images.githubusercontent.com/22761234/110225837-40b0e700-7f3d-11eb-9e42-213743eb1d43.png)

**Comment by calcastor** [comment]
fixed in versions 2.2.3 and 1.4.2 of kryta and kryta: one shot respectively
