### ISSUE TITLE
[Trench Warfare] Nerf Heavy

### ISSUE THREAD

**Issue by Brottweiler** [OvercastCommunity/Issues#6]
# Map name
Trench Warfare

## Is your feature request related to a problem?
Trench Warfare balancing.

## Describe the solution you'd like
The Heavy class is very hard to kill and should be nerfed.

## Describe alternatives you've considered
Consider removing the Protection 1 enchantment from all armor except the chestplate.

**Comment by Pugzy** [comment]
Could be fixed in https://github.com/OvercastCommunity/PrivateMaps/commit/8116f396bab502baf6a840a92380d30f1182a722.

I will try to catch a match and live and see how it plays with these changes.

**Comment by Pugzy** [comment]
I'm happy with this for now. 
The strength throwing guy seems a little OP now but can address this later.
