### ISSUE TITLE
[Pipe Palace] Can't place blocks at the end of pipes

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastCommunity/Issues#69]
![Capture](https://user-images.githubusercontent.com/7937351/109409295-a27eb900-795f-11eb-88e2-34ab3df141b3.PNG)

**Comment by Pugzy** [comment]
I checked the entire map when this comment was posted in Discord.

Found nothing unusual so would need more info to fix.

**Comment by CrazyisCreeps** [comment]
Yea I'm not too sure either, and it seems like the one who reported the issue on discord has left discords
