### ISSUE TITLE
[Tridente] Wrong label on blue side

### ISSUE THREAD

**Issue by drmzio** [OvercastCommunity/Issues#74]
# Map name
Tridente

## Describe the bug
The label at **blue base** says "Teleport to Blue Base here" (see screenshot)

## Expected behavior
Label should say "Teleport to Red Base here"

## Screenshots
![Image 2021-03-24 at 6 46 17 PM](https://user-images.githubusercontent.com/6914518/112406617-bf45ac80-8cd1-11eb-95c4-0a60673b82de.jpg)

### Additional context
N/A

**Comment by Pugzy** [comment]
Should be fixed in https://github.com/OvercastCommunity/CommunityMaps/commit/60386c0c0d25fe168ee6ed12b22a2697412f5455.
