### ISSUE TITLE
[Tetrad] Spawn roof skip

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/Issues#77]
# Map name
Tetrad

## Describe the bug
if you manage to build up to the roof of another teams spawn you can just jump onto it and down into the woolroom courtyard area which defeats the point of the defence walls on either sides

## Expected behavior
I expected a <aaply enter=> region to prevent people from going onto the roof

## Screenshots
I did not get a screenshot but this bug's easy to test for yourself

### Additional context
I assume this also works on your own teams base but I haven't tried it and seems pretty useless

**Comment by Pugzy** [comment]
I've always seen this as an intended feature.

**Comment by calcastor** [comment]
I would also say that this is an intended feature that was likely considered when the map was originally created.
