### ISSUE TITLE
[Spaceship Battles II] Spawn is breakable

### ISSUE THREAD

**Issue by Antnecb** [OvercastCommunity/Issues#78]
# Map name
Spaceship Battles II

## Describe the bug
It's possible to destroy the spawn area, allowing a player to break the area directly under the spawn region, causing players to immediately fall to their death after spawning. Additionally, it's impossible to place blocks in this area, so if a player were to break it, a Moderator or Map Developer would be needed in order to fix it.

## Expected behavior
A region to deny breaking blocks should be added around the spawn drop ship.

## Screenshots
Broken spawn
![2021-06-16_17 34 24](https://user-images.githubusercontent.com/26776253/122612615-6fb51980-d051-11eb-9d9d-c7b50f86f246.png)

Fixed with WorldEdit
![2021-06-16_17 30 18](https://user-images.githubusercontent.com/26776253/122612671-88bdca80-d051-11eb-8006-ce2ce081c43e.png)

### Additional context
N/A

**Comment by CoWinkKeyDinkInc** [comment]
Fixed in https://github.com/OvercastCommunity/PrivateMaps/commit/8c8d41187bb2974a0404f28ff4cef69334da58be
