### ISSUE TITLE
[Hide n' Seek] Remove dropped items from structures

### ISSUE THREAD

**Issue by drmzio** [OvercastCommunity/Issues#79]
# Map name
Hide n' Seek

## Describe the bug
When the structures disappear, they drop these items:
- White carpet
- Wooden pressure plate
- Wooden door

Players with invisibility accidentally pick up the items and are easily found by the seekers.

## Expected behavior
Items should not be dropped. These items should be in the map XML under `itemremove`

## Screenshots

![Image 2021-07-01 at 12 10 48 PM](https://user-images.githubusercontent.com/6914518/124178908-e812d600-da66-11eb-8705-39fdda29268c.jpg)

**Comment by CoWinkKeyDinkInc** [comment]
Fixed in https://github.com/OvercastCommunity/PrivateMaps/commit/8c914f30b4d20cccbc54947ad2df494c3bc2f48b
