### ISSUE TITLE
[Mushroom Gorge] Wool Room Bedrock is too thin, allowing for clipping from below via ridable entities

### ISSUE THREAD

**Issue by rinOfTheStars** [OvercastCommunity/Issues#81]
# Map name
Mushroom Gorge

## Describe the bug
Due to the bedrock below the Wool Rooms in Gorge being 1 thick, with a large tunnelable area below it, players are able to clip though the bedrock using boats.

## Expected behavior
Players should not be able to clip into wool rooms.

## Screenshots
https://i.imgur.com/CdcNuwO.png location (all 4 wool rooms have this issue)
Footage of a replication of this clip in singleplayer: https://youtu.be/9HK_gtUD97U

### Additional context
I suggest just outright removing the breakable terrain under the wool rooms, replacing it with bedrock, as its kinda janky to begin with (players on the attacking team can go under it while defenders can not).

**Comment by calcastor** [comment]
fixed pushed today
