### ISSUE TITLE
[Hide and seek (all maps)] a sponsor issue!

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/Issues#82]
Currently right now, almost every hide and seek map is not sponsorable... this includes store, clue, classic and shahedini. But for some reason you can sponsor shahedini: zombies.

now I’m all ears for being able to sponsor arcade maps but shouldn’t it be more consistent... why can we only sponsor one map from hide n seek... and if you allow us to sponsor all hide n seek why shouldn’t all maps e.g. dropper maps n such be sponsorable.

now this isn’t me telling anyone what to do... I’m just pointing out some inconsistencies which I hope you mapdev will look into and fix :)

**Comment by Brottweiler** [comment]
I have not confirmed this, but I think the reason the Zombies version is sponsorable is that when someone dies, they become zombies and can continue playing. The other hide & seek maps are Blitz, which is bad for user experience.

Basically what this means is that if you plan to make a hide & seek map, make it zombies. They are much better UX wise.

**Comment by technodono** [comment]
> 
> 
> I have not confirmed this, but I think the reason the Zombies version is sponsorable is that when someone dies, they become zombies and can continue playing. The other hide & seek maps are Blitz, which is bad for user experience.
> 
> Basically what this means is that if you plan to make a hide & seek map, make it zombies. They are much better UX wise.

Ah, thanks for clearing that up... my apologies
