### ISSUE TITLE
Hide n Seek Community

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastCommunity/Issues#84]
I won't fix this for who knows how long so if someone else thinks this affects gameplay enough they can handle it?

Anyways this section of the plot needs to be removed, as it passes over the plot borders and therefore does not disappear when the plot does. 
![image](https://github.com/OvercastCommunity/Issues/assets/7937351/a6c4f96f-012e-4084-9b61-73824a6258f5)

I believe that's the Applenick plot

**Comment by mitchts** [comment]
https://github.com/OvercastCommunity/CommunityMaps/commit/bdab858e0fcf18b0877055901ef1b503f7da024f
