### ISSUE TITLE
[Roofed Sunset] Blue can craft red wool without leaving their side

### ISSUE THREAD

**Issue by 42null** [OvercastCommunity/Issues#85]
# Roofed Sunset

## Describe the bug
Blue players can break the string on their side to make white wool, then craft red dye with a poppy also on their side to make red wool.

## Expected behavior
Poppies should not drop on this map or crafting dyed red wool should be disabled. However, using dye to change armor color is fun and harmless, I will look to see if I can get the XML to deny crafting the dyed red wool.

**Comment by TheRealPear** [comment]
Thanks for reporting. I've made it so you cannot craft specific wool colors required to win the game. However, players can still craft the other wool colors and dyes as well. To answer your question in the last sentence, you can set the [`craftable` attribute to false for wools](https://pgm.dev/docs/modules/objectives/ctw#wool-attributes).

**Comment by 42null** [comment]
That's great! I know I said I would take a look about looking at the XML but I have 0 experience with that setup here and I had no idea what I was looking for.
